version: '3.4'

services:
  contents-vis-frontend:
    image: contents-vis-frontend
    build: .
    environment:
      NODE_ENV: production
      REACT_APP_BACKEND_URL: http://localhost:5000
    ports:
      - "80:80"